# ---- Stage 1: build the Vue admin frontend (incl. email-builder) ----
FROM node:20-bookworm AS frontend

# Cypress ships as a devDependency but its binary is never needed to build.
ENV CYPRESS_INSTALL_BINARY=0

WORKDIR /build

COPY frontend ./frontend
# postinstall of the admin frontend copies altcha assets into ../static/.
COPY static ./static

# Email-builder first (mirrors `make build-email-builder`).
WORKDIR /build/frontend/email-builder
RUN corepack enable \
    && yarn install --no-immutable \
    && yarn build \
    && yarn cache clean \
    && rm -rf node_modules

# Main admin frontend (mirrors `make build-frontend`).
WORKDIR /build/frontend
RUN mkdir -p public/static/email-builder \
    && cp -r email-builder/dist/* public/static/email-builder/ \
    && yarn install --no-immutable \
    && yarn build \
    && yarn cache clean \
    && rm -rf node_modules email-builder/node_modules

# ---- Stage 2: build the Go backend and pack static assets into it ----
FROM golang:1.27-bookworm AS backend
WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY --from=frontend /build/frontend/dist ./frontend/dist
# Generated by the frontend postinstall (gitignored, so not in COPY . .).
COPY --from=frontend /build/static/public/static/altcha.umd.js ./static/public/static/altcha.umd.js

RUN CGO_ENABLED=0 go build -o patra -ldflags="-s -w" ./cmd \
    && STUFFBIN_BIN="$(go env GOPATH)/bin/stuffbin" \
    && go install github.com/knadh/stuffbin/... \
    && "$STUFFBIN_BIN" -a stuff -in patra -out patra \
        config.toml.sample \
        schema.sql queries:/queries permissions.json \
        static/public:/public \
        static/email-templates \
        frontend/dist:/admin \
        i18n:/i18n

# ---- Stage 3: minimal runtime (unchanged behaviour) ----
FROM alpine:latest

# Install dependencies
RUN apk --no-cache add ca-certificates tzdata shadow su-exec

# Set the working directory
WORKDIR /patra

# Copy the packed binary from the builder.
COPY --from=backend /build/patra .
COPY config.toml.sample config.toml

# Copy the entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/

# Make the entrypoint script executable
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Expose the application port
EXPOSE 9000

# Set the entrypoint
ENTRYPOINT ["docker-entrypoint.sh"]

# Define the command to run the application
CMD ["./patra"]
